
.before-script-secrets-anchor: &export-env-vars-script
  # Access the value of the file variable indirectly
  - eval "FILE_CONTENT=\$$ENV_FILE_VARIABLE"
  - cat "$FILE_CONTENT" > .env
  - set -o allexport &&
    source .env &&
    set +o allexport