
services:
  backend:
    container_name: messaging_backend
    build:
        context: ./backend
        dockerfile: Dockerfile
    env_file:
      - ./backend/.env.demo
    expose: 
      - 8000
    depends_on:
      - postgres
      - redis
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    restart: unless-stopped


  postgres:
    image: postgres:15
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.demo

  redis:
    image: redis
    expose:
      - 6379
    command: [ 'redis-server', '--appendonly', 'yes' ]
    restart: unless-stopped


  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: