ARG BASE_IMAGE
WORKDIR /usr/src/app

# Final stage
FROM $BASE_IMAGE AS final
COPY /usr/src/app/.venv/ /usr/src/app/.venv/
# Set the PATH to include the virtualenv's bin
ENV PATH="/usr/src/app/.venv/bin:$PATH"

COPY ./ ./

RUN chmod +x wait-for-postgres.sh docker-entrypoint.sh
EXPOSE 8000
# for debugging only
#CMD ["tail", "-f", "/dev/null"]
ENTRYPOINT ["sh", "./docker-entrypoint.sh"]

