ARG BASE_IMAGE
FROM $BASE_IMAGE
WORKDIR /usr/src/app

# Set the PATH to include the virtualenv's bin
ENV PATH="/usr/src/app/.venv/bin:$PATH"

# set default username
ARG APP_USER_NAME=appuser
# Create a non-root user and group
RUN groupadd -r "$APP_USER_NAME" \
    && useradd -r -g "$APP_USER_NAME" -m "$APP_USER_NAME" \
    && chown -R "$APP_USER_NAME" /usr/src/app

COPY ./ ./

# set permissions for the logs directory
RUN mkdir -p /usr/src/app/logs
RUN chown -R "$APP_USER_NAME":"$APP_USER_NAME" /usr/src/app/logs

RUN chmod +x wait-for-postgres.sh docker-entrypoint.sh
EXPOSE 8000

# Switch to the non-root user
USER "$APP_USER_NAME"

ENV ENV=test

# for debugging only
#CMD ["tail", "-f", "/dev/null"]
ENTRYPOINT "./docker-entrypoint.sh"

