services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.dev

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: [ 'redis-server', '--appendonly', 'yes' ]
    restart: unless-stopped


volumes:
  postgres_data:
  redis_data: