ARG BASE_IMAGE

RUN echo "pwd"
RUN echo "ls -htal"

# Final stage
FROM $BASE_IMAGE AS final
COPY /usr/src/app/.venv/ /usr/src/app/.venv/
# Set the PATH to include the virtualenv's bin
ENV PATH="/usr/src/app/.venv/bin:$PATH"

COPY ./ ./

EXPOSE 8003
# for debugging only
#CMD ["tail", "-f", "/dev/null"]
CMD ENV=demo python -m src.main