# Base stage
FROM python:3.10-slim AS base
WORKDIR /usr/src/app

ENV PYTHONFAULTHANDLER=1 \
    PYTHONHASHSEED=random \
    PYTHONUNBUFFERED=1

RUN apt-get update &&\
    apt-get install -y --no-install-recommends gcc libffi-dev g++ && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Dependencies stage
FROM base AS dependencies
COPY ./Pipfile ./Pipfile.lock ./
RUN pip install --no-cache-dir pipenv

# installs dependecies in .venv
ENV PIPENV_VENV_IN_PROJECT=1
RUN pipenv install --ignore-pipfile --dev  # including dev dependencies for test


