ARG BASE_IMAGE
FROM $BASE_IMAGE
WORKDIR /usr/src/app

# Set the PATH to include the virtualenv's bin
ENV PATH="/usr/src/app/.venv/bin:$PATH"

COPY ./ ./

EXPOSE 8003
# for debugging only
#CMD ["tail", "-f", "/dev/null"]

ENV ENV=test
ENTRYPOINT "python -m src.main"