"""user tgid and last active at

Revision ID: 579b3f7a5e4f
Revises: 62fea801a274
Create Date: 2024-11-08 17:55:49.164783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '579b3f7a5e4f'
down_revision: Union[str, None] = '62fea801a274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(), nullable=False,
                                     server_default=sa.text('NOW()')))  # <-- added
    op.add_column('users', sa.Column('telegram_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'last_active_at')
    # ### end Alembic commands ###
