"""contacts_association_object_step3

Revision ID: 62fea801a274
Revises: a5a03e988d2c
Create Date: 2024-11-01 00:06:15.974293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fea801a274'
down_revision: Union[str, None] = 'a5a03e988d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts1_created_at', table_name='contacts')
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)

    op.alter_column('contacts', 'id', server_default=sa.text('uuid_generate_v4()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'id', server_default=None)

    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.create_index('ix_contacts1_created_at', 'contacts', ['created_at'], unique=False)
    # ### end Alembic commands ###
