"""user contacts col uuid, step5

Revision ID: 889b51cb531a
Revises: 8dca7ec1bef0
Create Date: 2024-10-26 22:37:32.025811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889b51cb531a'
down_revision: Union[str, None] = '8dca7ec1bef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uuid_id', new_column_name='id', type_=sa.UUID(), existing_nullable=False)
    op.create_unique_constraint('uq_users_id', 'users', ['id'])

    op.alter_column('contacts', 'contact_uuid_id', new_column_name='contact_id', type_=sa.UUID(), existing_nullable=False)
    op.alter_column('contacts', 'user_uuid_id', new_column_name='user_id', type_=sa.UUID(), existing_nullable=False)

    op.drop_constraint('fk_contacts_contact_uuid_id_users', 'contacts', type_='foreignkey')
    op.drop_constraint('fk_contacts_user_uuid_id_users', 'contacts', type_='foreignkey')

    op.alter_column('messages', 'user_to_uuid_id', new_column_name='user_to_id', type_=sa.UUID(), existing_nullable=False)
    op.alter_column('messages', 'user_from_uuid_id', new_column_name='user_from_id', type_=sa.UUID(), existing_nullable=False)
    op.alter_column('messages', 'uuid_id', new_column_name='id', type_=sa.UUID(), existing_nullable=False)

    op.drop_constraint('fk_messages_user_from_uuid_id_users', 'messages', type_='foreignkey')
    op.drop_constraint('fk_messages_user_to_uuid_id_users', 'messages', type_='foreignkey')

    op.drop_constraint('uq_users_uuid_id', 'users', type_='unique')

    op.create_foreign_key(op.f('fk_contacts_user_id_users'), 'contacts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_contacts_contact_id_users'), 'contacts', 'users', ['contact_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_messages_user_to_id_users'), 'messages', 'users', ['user_to_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_messages_user_from_id_users'), 'messages', 'users', ['user_from_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_messages_user_from_id_users'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('fk_messages_user_to_id_users'), 'messages', type_='foreignkey')

    op.drop_constraint(op.f('fk_contacts_contact_id_users'), 'contacts', type_='foreignkey')
    op.drop_constraint(op.f('fk_contacts_user_id_users'), 'contacts', type_='foreignkey')

    op.create_unique_constraint('uq_users_uuid_id', 'users', ['uuid_id'])

    op.alter_column('messages', 'id', new_column_name='uuid_id', type_=sa.UUID(), existing_nullable=False)
    op.alter_column('messages', 'user_from_id', new_column_name='user_from_uuid_id', type_=sa.UUID(),
                    existing_nullable=False)
    op.alter_column('messages', 'user_to_id', new_column_name='user_to_uuid_id', type_=sa.UUID(),
                    existing_nullable=False)

    op.create_foreign_key('fk_messages_user_to_uuid_id_users', 'messages', 'users', ['user_to_uuid_id'], ['uuid_id'],
                          ondelete='CASCADE')
    op.create_foreign_key('fk_messages_user_from_uuid_id_users', 'messages', 'users', ['user_from_uuid_id'],
                          ['uuid_id'], ondelete='CASCADE')

    op.alter_column('contacts', 'user_id', new_column_name='user_uuid_id', type_=sa.UUID(), existing_nullable=False)
    op.alter_column('contacts', 'contact_id', new_column_name='contact_uuid_id', type_=sa.UUID(),
                    existing_nullable=False)

    op.create_foreign_key('fk_contacts_user_uuid_id_users', 'contacts', 'users', ['user_uuid_id'], ['uuid_id'],
                          ondelete='CASCADE')
    op.create_foreign_key('fk_contacts_contact_uuid_id_users', 'contacts', 'users', ['contact_uuid_id'], ['uuid_id'],
                          ondelete='CASCADE')

    op.alter_column('users', 'id', new_column_name='uuid_id', type_=sa.UUID(), existing_nullable=False)
    op.drop_constraint('uq_users_id', 'users', type_='unique')

    # ### end Alembic commands ###

