"""user contacts col uuid, step1

Revision ID: a9c459dd00ed
Revises: 50d33e683155
Create Date: 2024-10-25 16:11:08.214413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c459dd00ed'
down_revision: Union[str, None] = '50d33e683155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the uuid-ossp extension if it doesn't exist
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";") # <-- for the server_default function to work
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('uuid_id', sa.Uuid(), nullable=False, server_default=sa.text('uuid_generate_v4()')))  # <-- server_default populates values for existing rows with default
    op.create_index(op.f('ix_messages_uuid_id'), 'messages', ['uuid_id'], unique=True)
    op.add_column('users', sa.Column('uuid_id', sa.Uuid(), nullable=False, server_default=sa.text('uuid_generate_v4()')))  # <-- server_default populates values for existing rows with default
    op.create_index(op.f('ix_users_uuid_id'), 'users', ['uuid_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid_id'), table_name='users')
    op.drop_column('users', 'uuid_id')
    op.drop_index(op.f('ix_messages_uuid_id'), table_name='messages')
    op.drop_column('messages', 'uuid_id')
    # ### end Alembic commands ###
